### ISSUE TITLE
Solve `TypeError: 'bool' object is not callable` for `Renderer`

### ISSUE THREAD

**Issue by a-lemus96** [a-lemus96/fs-nerf#65]
Solve `TypeError: 'bool' object is not callable` for `Renderer`
```
❯ python run-nerf.py --debug
Device: NVIDIA GeForce RTX 3090
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/home/lemus/miniconda3/envs/nerf/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning:

The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.

/home/lemus/miniconda3/envs/nerf/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning:

Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.

Loading model from: /home/lemus/miniconda3/envs/nerf/lib/python3.11/site-packages/lpips/weights/v0.1/vgg.pth
[NeRF]:   0%|                                                                                                                      | 0/8000 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/lemus/projects/fs-nerf/src/run-nerf.py", line 534, in <module>
    main()
  File "/home/lemus/projects/fs-nerf/src/run-nerf.py", line 434, in main
    train(
  File "/home/lemus/projects/fs-nerf/src/run-nerf.py", line 225, in train
    renderer.train()
TypeError: 'bool' object is not callable
```

_Originally posted by @a-lemus96 in https://github.com/a-lemus96/fs-nerf/issues/61#issuecomment-1984670796_

**Comment by a-lemus96** [comment]
The problem seems to be due to conflicts between `train` attribute and `train` method. Class members must me renamed to remove conflict.
